mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='account-register'),
    path('delete/', views.delete_profile, name='account-delete'),
    path('login/', views.login_, name='account-login'),
    path('logout/', views.logout, name='account-logout'),
    path('profile-settings/', views.update_profile, name='account-profile'),
    path('profile/<author_slug>', views.profile, name='profile'),
    path('fufollow/<slug>', views.follow_unfollow, name='follow-unfollow'),
    path('network-stats/<slug>', views.net_stats, name='net-stats'),
]

mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='blog-index'),
    path('post/<slug>', views.post, name='blog-post'),
    path('create/', views.make_post, name='post-blog'),
    path('query/', views.query, name='blog-query'),
    path('upvote/<slug>', views.upvote, name='blog-upvote'),
    path('downvote/<slug>', views.downvote, name='blog-downvote'),
    path('haha-comment/<slug>', views.haha_comment, name='comment-haha'),
    path('haha-reply/<slug>', views.haha_reply, name='reply-haha'),
    path('delete-post/<slug>', views.del_post, name='delete-post'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about-author/', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('accounts.urls', 'account'), namespace='accounts')),
    path('tinymce/', include('tinymce.urls')),
    path(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/accounts/forms.py
from django import forms
from django.forms.fields import FilePathField
from django.forms.models import ModelForm
from blog.models import Author

class UpdateForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ("fullname", "bio", "profile_pic")

mysite/accounts/views.py
from django.contrib import auth
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as lt
from .forms import UpdateForm
from blog.models import Post, Author, AuthorMeta
from django.contrib.auth import get_user


# Create your views here.
def register(req):
    context = {}
    form = UserCreationForm(req.POST or None)
    if req.method == "POST":
        if form.is_valid():
            new_user = form.save()
            authenticate(req, username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(req, new_user)
            return redirect("accounts:account-profile")
    context.update({
        "form": form,
        "title": "Signup",
    })
    return render(req, 'register.html', context)

def login_(req):
    context = {}
    form = AuthenticationForm(req, data=req.POST)
    if req.method == "POST":
        if form.is_valid():
            user = authenticate(req, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(req, user)
                return redirect("blog:blog-index")
    context.update({
        'form': form,
        "title": "Login"
    })
    return render(req, 'login.html', context)


@login_required
def update_profile(req):
    context = {}
    user = req.user
    form = UpdateForm(req.POST, req.FILES)
    author = Author.objects.filter(user=user)
    if req.method == "POST":
        if form.is_valid():
            updated_profile = form.save(commit=False)
            updated_profile.user = user
            print("user id: ", user.id)
            author.update_or_create(
                user_id=user.id,
                fullname=updated_profile.fullname,
                bio=updated_profile.bio,
                profile_pic=updated_profile.profile_pic
            )
            return redirect("blog:blog-index")
    context.update({
        "form": form,
        "Title": "Update Profile",
        'user': author
    })
    return render(req, 'profile.html', context)

@login_required
def logout(req):
    lt(req)
    return redirect("blog:blog-index")

@login_required
def profile(req, author_slug):
    context = {}
    user = req.user
    author =  Author.objects.get(slug = author_slug)
    meta = AuthorMeta.objects.get(user = author)
    posts = Post.objects.filter(user=author)[::-1]
    context.update({
        'author': author,
        'posts': posts,
        'meta': meta,
    })
    return render(req, 'profile-pub.html', context)

@login_required
def delete_profile(req):
    user = req.user
    user.delete()

    return redirect("blog:blog-index")

@login_required
def follow_unfollow(req, slug):
    if req.method == "POST":
        # Current User
        user = req.user
        current_author = Author.objects.get(user = user)
        current_author_meta = AuthorMeta.objects.get(user = current_author)
        
        # Viewed User
        id = req.POST.get("author_id")
        author = Author.objects.get(id = id)
        author_meta = AuthorMeta.objects.get(user = author)
        
        # Actions
        if current_author in [i for i in author_meta.followers.all()]:
            print("Unfollowed")
            author_meta.followers.remove(current_author)
            current_author_meta.following.remove(author)
        else:
            print("Followed.")
            author_meta.followers.add(current_author)
            current_author_meta.following.add(author)
        return redirect("accounts:profile", slug)

@login_required
def net_stats(req, slug):
    # Current user
    current_user = req.user
    current_author = Author.objects.get(user = current_user)
    current_author_meta = AuthorMeta.objects.get(user = current_author)

    # Viewed user
    author = Author.objects.get(slug = slug)
    author_meta = AuthorMeta.objects.get(user = author)
    print([i for i in author_meta.followers.all()])
    context = {
        'author_meta' : author_meta,
        'current_author_meta': current_author_meta
        }
    return render(req, "network-stats.html", context)

mysite/accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Font Awesome-->
    <link href="{% static 'fontawesome_free/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <!--Material CSS CDNs-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    <!--Custom JS-->
    <script type="text/javascript" src="{% static 'js/blog/index.js' %}"></script>
    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/blogs/users/style.css' %}">
    <title>Silly | Login</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <form method="POST" class="col s12" id="login-form">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        {{form.username}}
                        <!-- <input id="username" type="text" class="validate" required> -->
                        <label for="username">Username</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{form.password}}
                        <!-- <input id="password" type="password" class="validate" minlength="6" name="password" required> -->
                        <label for="password">Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <button class="btn btn-large btn-register waves-effect waves-light" value="login" type="submit" name="action">Login
                            <i class="material-icons right">done</i>
                        </button>
                    </div>
                </div>
                <a href="{%url 'accounts:account-register'%}">New User? Create an account first! </a>
            </form>
        </div>
    </div>    
</body>
</html>

mysite/accounts/templates/network-stats.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!--JQuery-->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        
        <!--Material CSS CDNs-->
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        <!--Custom JS-->
        <script type="text/javascript" src="{% static 'js/blog/index.js' %}"></script>

        <!--Custom CSS-->
        <link rel="stylesheet" href="{% static 'css/blogs/style.css' %}">
        
        <title>Network Stats</title>
    </head>
    <body>
        <div class="container">
            <ul class="tabs row">
                <li class="tab col s6"><a href="#followers">Followers</a></li>
                <li class="tab col s6"><a href="#following">Following</a></li>
            </ul>
            <div class="row">
                <!-- Followers -->
                <div id="followers" class="container col s12">
                    <ul class="collection">
                        {% for follower in author_meta.followers.all %}
                        <li class="collection-item avatar">
                            <img src="{{  follower.profile_pic.url }}" alt="{{ follower.fullname }}" class="circle"></img>
                            <span class="title">{{ follower.fullname | title }}</span>
                            {% if current_author_meta.user == author_meta.user %}
                                {% if follower in current_author_meta.following.all %}
                                <a href="{{follower.get_url}}" class="secondary-content">View Posts</a>
                                <form method="POST" action="{% url 'accounts:follow-unfollow' follower.slug  %}">
                                    {% csrf_token %}
                                    <button name="author_id" value="{{follower.id}}" class="waves-effect waves-light btn">
                                        Unfollow
                                    </button>
                                </form>
                                {% else %}
                                <a href="{{follower.get_url}}" class="secondary-content">View Posts</a>
                                <form method="POST" action="{% url 'accounts:follow-unfollow' follower.slug  %}">
                                    {% csrf_token %}
                                    <button name="author_id" value="{{follower.id}}" class="waves-effect waves-light btn">
                                        Follow Back
                                    </button>
                                </form>
                                {% endif %}
                            {% else %}
                                {% if follower in current_author_meta.following.all %}
                                <a href="{{follower.get_url}}" class="secondary-content">View Posts</a>
                                <form method="POST" action="{% url 'accounts:follow-unfollow' follower.slug  %}">
                                    {% csrf_token %}
                                    <button name="author_id" value="{{follower.id}}" class="waves-effect waves-light btn">
                                        Unfollow
                                    </button>
                                </form>
                                {% else %}
                                <a href="{{follower.get_url}}" class="secondary-content">View Posts</a>
                                <form method="POST" action="{% url 'accounts:follow-unfollow' follower.slug  %}">
                                    {% csrf_token %}
                                    <button name="author_id" value="{{follower.id}}" class="waves-effect waves-light btn">
                                        Follow
                                    </button>
                                </form>
                                {% endif %}
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Following -->
                <div id="following" class="container col s12">
                    <ul class="collection">
                        {% for following in author_meta.following.all %}
                        <li class="collection-item avatar">
                            <img src="{{  following.profile_pic.url }}" alt="{{ followig.fullname }}" class="circle">
                            <span class="title">{{ following.fullname | title }}</span>
                            {% if following in current_author_meta.following.all %}
                            <a href="{{following.get_url}}" class="secondary-content">View Posts</a>
                            <form method="POST" action="{% url 'accounts:follow-unfollow' following.slug  %}">
                                {% csrf_token %}
                                <button name="author_id" value="{{following.id}}" class="waves-effect waves-light btn">
                                    Unfollow
                                </button>
                            </form>
                            {% else %}
                            <a href="{{following.get_url}}" class="secondary-content">View Posts</a>
                            <form method="POST" action="{% url 'accounts:follow-unfollow' following.slug  %}">
                                {% csrf_token %}
                                <button name="author_id" value="{{following.id}}" class="waves-effect waves-light btn">
                                    Follow
                                </button>
                            </form>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
        </div>
    </body>
</html>

mysite/accounts/templates/profile.html
{% extends 'partials/partials.html' %}
{% load static %}
{% block title %}
Silly | Dashboard
{% endblock title %}
{% block body %}
<div class="row">
  <form action="." method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="update" class="btn waves-effect">
</form>
</div>
<div class="container">
  <a class="waves-effect waves-light red btn modal-trigger secondary-content" href="#delete">Delete Account</a>
  
  <!-- Modal Structure -->
  <div id="delete" class="modal">
    <div class="modal-content">
      <h4>Are you sure???</h4>
      <p>Deleting your account means you and <b>your {{user.num_posts}} posts</b> will be <b>non existent</b> in this platform. Your <b><i>69 friend(s)</i> can no more</b> see your fun stuff here. If you start again, you have to <b>start from the begining</b>. We would recommend rather <b>staying off this platform</b> for few days and <i>returning back again if you want to</i>, or leave it as it is.<br>Thanks For Your Attention</p>
    </div>
    <div class="modal-footer">
      <a class="modal-close waves-effect waves-green btn-flat">Shit! I clicked it by mistake</a>
      <a href="{% url 'accounts:account-delete' %}" class="modal-close waves-effect waves-green red btn-flat">Yes, delete it!</a>
    </div>
  </div>
    <!-- Profile Pic -->
    <!-- <div class="col s3">
        <img class="materialboxed rounded" width="180" src="{}" alt="pfp">
        <form action="." method="POST" enctype="multipart/form-data">
            <div class="file-field input-field">
                <div class="btn waves-effect waves-teal">
                    <span>Change</span>
                    <input type="file">
                </div>
                <div hidden class="file-path-wrapper">
                    <input class="file-path validate" type=".png, .jpg, .jpeg" value="upload">
                </div>
            </div>
        </form>
    </div> -->
    <!-- Profile Details -->
    <!-- <h2>Profile</h2>
    <div class="col s9">
        <input class="username" value="@i_am_lol"></input>
        <div class="row">
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s12">
                        <textarea id="bio" class="bio materialize-textarea">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.</textarea>
                    </div>
                </div>
            </form>
        </div>
          <h2>Connections</h2> -->
          <!-- Facebook Link -->
          <!-- <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <input id="facebook-url" type="url" value='https://facebook.com/lol'>
                  <label for="facebook-url">Connect Facebook</label>
                </div>
              </div>
            </form>
          </div> -->
          <!-- Instagram Link -->
          <!-- <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <input id="facebook-url" type="url" value='https://isntagram.com/lol'>
                  <label for="facebook-url">Connect Instagram</label>
                </div>
              </div>
            </form>
          </div> -->
          <!-- Twitter Link -->
          <!-- <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <input id="facebook-url" type="url" value='https://twitter.com/lol'>
                  <label for="facebook-url">Connect Twitter</label>
                </div>
              </div>
            </form>
          </div> -->
                  <!-- Personal -->
        <!-- <h2>Account Details</h2>
        <form>
            <div class="row">
              <div class="input-field col s6">
                <input id="first-name" type="text" class="validate" value="John">
                <label for="first-name">First Name</label>
              </div>
              <div class="input-field col s6">
                <input id="last-name" type="text" class="validate" value="Doe">
                <label for="last-name">Last Name</label>
              </div>
            </div>
        </form>
        <div class="row">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s12">
                <input id="email" type="email" class="validate" value="profile@email.com">
                <label for="email">Email</label>
                <span class="helper-text" data-error="Please enter a valid email" data-success="Seems OK!"></span>
              </div>
            </div>
          </form>
        </div>
        <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <input id="prev-paswword" type="password" class="validate">
                  <label for="prev-password">Previous Password</label>
                </div>
              </div>
            </form>
          </div>
          <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <input id="new-paswword" type="password" class="validate">
                  <label for="new-password">New Password</label>
                </div>
              </div>
            </form>
          </div>
          <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <input id="confirm-paswword" type="password" class="validate">
                  <label for="confirm-password">Confirm Password</label>
                </div>
              </div>
            </form>
          </div>
        
        <div class="right-align">
            <a class="btn btn-floating waves-effect waves-light btn-large">
                <i class="material-icons">save</i>
            </a>
        </div>
    </div> -->
    <!-- Profile Details End -->
</div>
{% endblock body %}
{% block sidenav %}
<!-- Sidenav -->
<li href="#" class="waves-effect collection-item"><h5>Trending</h5></li>
<ul class="collection">
    <li href="#" class="collection-item">Post Title 1</li>
    <li href="#" class="collection-item">Post Title 2</li>
    <li href="#" class="collection-item">Post Title 3</li>
    <li href="#" class="collection-item">Post Title 4</li>
    <li href="#" class="collection-item">Post Title 5</li>
</ul>
<li href="#" class="waves-effect collection-item"><h5>Recents</h5></li>
<ul class="collection">
    <li href="#" class="collection-item">Post Title 1</li>
    <li href="#" class="collection-item">Post Title 2</li>
    <li href="#" class="collection-item">Post Title 3</li>
    <li href="#" class="collection-item">Post Title 4</li>
    <li href="#" class="collection-item">Post Title 5</li>
</ul>
<li href="#" class="waves-effect collection-item"><h5>Catagories</h5></li>
<ul class="collection">
    <li href="#" class="waves-effect collection-item">Cat 1</li>
    <li href="#" class="waves-effect collection-item">Cat 2</li>
    <li href="#" class="waves-effect collection-item">Cat 3</li>
    <li href="#" class="waves-effect collection-item">Cat 4</li>
</ul>
{% endblock sidenav %}

mysite/accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Font Awesome-->
    <link href="{% static 'fontawesome_free/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <!--Material CSS CDNs-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    <!--Custom JS-->
    <script type="text/javascript" src="{% static 'js/blog/index.js' %}"></script>
    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/blogs/users/style.css' %}">
    <title>Silly | {{title}}</title>
</head>
<body>
  <div class="container">
    <div class="row">
      <form method="POST" action="." class="col s12" id="reg-form">
        {% csrf_token %}
        {{form.as_table}}
        <!-- <div class="row">
          <div class="input-field col s12">
            <label for="username">Username</label>
            {{form.username}}
          </div>
        </div>
        <div class="row"> 
          <div class="input-field col s12">
            <label for="password1">Password</label>
            {{form.password1}}
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <label for="password2">Confirm Password</label>
            {{form.password2}}
            <span id="message"></span>
          </div>
        </div> -->
        <div class="input-field col s6">
          <button class="btn btn-large btn-register waves-effect waves-light" type="submit" name="action">Register
            <i class="material-icons right">done</i>
          </button>
        </div>
      </form>
    </div>
    <a href="{% url 'accounts:account-login' %}" title="Login" class="ngl btn-floating btn-large waves-effect waves-light red"><i class="material-icons">input</i></a>
  </div>  
</body>
</html>