mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='account-register'),
    path('delete/', views.delete_profile, name='account-delete'),
    path('login/', views.login_, name='account-login'),
    path('logout/', views.logout, name='account-logout'),
    path('profile-settings/', views.update_profile, name='account-profile'),
    path('profile/<author_slug>', views.profile, name='profile'),
    path('fufollow/<slug>', views.follow_unfollow, name='follow-unfollow'),
    path('network-stats/<slug>', views.net_stats, name='net-stats'),
]

mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='blog-index'),
    path('post/<slug>', views.post, name='blog-post'),
    path('create/', views.make_post, name='post-blog'),
    path('query/', views.query, name='blog-query'),
    path('upvote/<slug>', views.upvote, name='blog-upvote'),
    path('downvote/<slug>', views.downvote, name='blog-downvote'),
    path('haha-comment/<slug>', views.haha_comment, name='comment-haha'),
    path('haha-reply/<slug>', views.haha_reply, name='reply-haha'),
    path('delete-post/<slug>', views.del_post, name='delete-post'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about-author/', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('accounts.urls', 'account'), namespace='accounts')),
    path('tinymce/', include('tinymce.urls')),
    path(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
import django
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation
from django_resized import ResizedImageField
from tinymce.models import HTMLField
from hitcount.models import HitCountMixin, HitCount
from taggit.managers import TaggableManager
from django.shortcuts import reverse
import datetime
from django.utils import timezone


# Create your models here.
User = get_user_model()

class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=50, blank=True)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    bio = HTMLField()
    points = models.IntegerField(default=0)
    profile_pic = ResizedImageField(size=[160, 90], quality=100, upload_to="author-pfp", default=None, blank=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.user.username}{timezone.now()}')
        super(Author, self).save(*args, **kwargs)

    def __str__(self):
        return self.fullname
    
    @property
    def num_posts(self):
        return Post.objects.filter(user=self).count()

    def get_url(self):
        return reverse("accounts:profile", kwargs={
            "author_slug": self.slug
        })

class AuthorMeta(models.Model):
    user = models.OneToOneField(Author, on_delete=models.CASCADE)
    followers = models.ManyToManyField(Author, related_name='followers', blank=True)
    following = models.ManyToManyField(Author, related_name='following', blank=True)

    @property
    def get_followers(self):
        return self.followers.all().count()

    @property
    def get_following(self):
        return self.following.all().count()

    def __str__(self):
        return self.user.fullname

class Catagory(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=400, unique=True, blank=True)

    class Meta:
        verbose_name_plural = "Catagories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Catagory, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    @property
    def num_posts(self):
        return Post.objects.filter(catagory=self).count()

    @property
    def last_post(self):
        return Post.objects.filter(catagory=self).latest("date")

class Reply(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    haha = models.ManyToManyField(User)

    def __str__(self):
        return self.content[:50]

    class Meta:
        verbose_name_plural = 'Replies'
    
    @property
    def get_hahas(self):
        num_hahas = self.haha.all().count()
        return num_hahas


class Comment(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    replies = models.ManyToManyField(Reply, blank=True)
    haha = models.ManyToManyField(User)

    def __str__(self):
        return self.content[:50]

    @property
    def get_hahas(self):
        num_hahas = self.haha.all().count()
        return num_hahas


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = HTMLField(max_length=500)
    catagory = models.ManyToManyField(Catagory)
    date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    upvotes = models.ManyToManyField(User, related_name='post_upvotes')
    downvotes = models.ManyToManyField(User, related_name='post_downvotes')
    tags = TaggableManager()
    comments = models.ManyToManyField(Comment, blank=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.title}{datetime.date.today()}{self.user.user.username}{timezone.now()}')
            print(self.slug)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("blog:blog-post", kwargs={
            "slug": self.slug
        })
    
    @property
    def get_score(self):
        upvotes = self.upvotes.all().count()
        downvotes = self.downvotes.all().count()
        return upvotes - downvotes

mysite/blog/forms.py
from django import forms
from .models import Catagory, Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'catagory', 'tags']

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Author, Catagory, Post, Comment, Reply
from .utils import update_views
from django.contrib.auth.decorators import login_required
from .forms import PostForm
# Create your views here.

def index(req):
    posts = Post.objects.all()[::-1]
    num_posts = Post.objects.all().count()
    num_users = Author.objects.all().count()
    
    context = {
        'posts': posts,
        'num_posts' : num_posts,
        'num_users' : num_users,
    }

    return render(req, 'home.html', context=context)

def post(req, slug):
    post = get_object_or_404(Post, slug=slug)

    if "comment-form" in req.POST:
        author = Author.objects.get(user=req.user)
        comment = req.POST.get("comment")
        new_comment, created = Comment.objects.get_or_create(user = author, content=comment)
        post.comments.add(new_comment.id)

    if "reply-form" in req.POST:
        author = Author.objects.get(user=req.user)
        reply = req.POST.get("reply")
        comment_id = req.POST.get("comment-id")
        comment_obj = Comment.objects.get(id=comment_id)
        new_reply, created = Reply.objects.get_or_create(user = author, content=reply)
        comment_obj.replies.add(new_reply)
    
    context = {
        'post': post
    }
    update_views(req, post)
    return render(req, 'post.html', context)

def query(req):
    return render(req, 'post-query.html')

@login_required
def make_post(req):
    context = {}
    form = PostForm(req.POST or None)
    if req.method == "POST":
        if form.is_valid():
            author = Author.objects.get(user=req.user)
            new_post = form.save(commit=False)
            new_post.user = author
            new_post.save()
            form.save_m2m()
            return redirect('blog:blog-index')
    context.update({
        'form': form,
        'title': 'Create A Post'
    })

    return render(req, 'create.html', context)


@login_required
def network_stats(req):
    return render(req, 'network-stats.html')


@login_required
def upvote(req, slug):
    post = get_object_or_404(Post, slug=slug)
    post.upvotes.add(req.user)
    return redirect("blog:blog-post", slug)

@login_required
def downvote(req, slug):
    post = get_object_or_404(Post, slug=slug)
    post.downvotes.add(req.user)
    return redirect("blog:blog-post", slug)

@login_required
def haha_comment(req, slug):
    if req.method == 'POST':
        id = req.POST.get("comment_id")
        comment = get_object_or_404(Comment, id = id)
        comment.haha.add(req.user)
        return redirect("blog:blog-post", slug)
    return redirect("blog:blog-post", slug)

@login_required
def haha_reply(req, slug):
    if req.method == 'POST':
        id = req.POST.get("reply_id")
        reply = get_object_or_404(Reply, id = id)
        reply.haha.add(req.user)
        return redirect("blog:blog-post", slug)
    return redirect("blog:blog-post", slug)

@login_required
def del_post(req, slug):
    if req.method == 'POST':
        id = req.POST.get("post_id")
        post = Post.objects.get(id = id)
        post.delete()
        return redirect("accounts:profile", slug)

mysite/blog/templates/partials/partials.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
    <!--Font Awesome-->
    <link href="{% static 'fontawesome_free/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>


    <!--Material CSS CDNs-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!--Custom JS-->
    <script type="text/javascript" src="{% static 'js/blog/index.js' %}"></script>

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/blogs/style.css' %}">
    
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <!--Navbar-->
    <!-- Catagories -->
    <ul id="catagory-drop" class="dropdown-content">
        <li><a href="/query">Cat 1</a></li>
        <li><a href="#!">Cat 2</a></li>
        <li><a href="#!">Cat 3</a></li>
    </ul>
    <!-- About -->
    <ul id="about-drop" class="dropdown-content">
        <li><a href="#">About Blog</a></li>
        <li><a href="/about-author">About Me</a></li>
    </ul>
    <!-- Account -->
    <ul id="account-drop" class="dropdown-content">
        {% if request.user.is_authenticated %}
        <li><a href="">Profile</a></li>
        <li><a href="{% url 'accounts:account-profile' %}">Profile Settings</a></li>
        <li class="divider"></li>
        <li><a href="{% url 'accounts:account-logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'accounts:account-login' %}">Login</a></li>
        <li><a href="{% url 'accounts:account-register' %}">SignUp</a></li>
        {% endif %}
    </ul>
    <nav>
        <div class="nav-wrapper">
            <div class="container">
                <a href="/" class="brand-logo">Silly</a>
            </div>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'blog:blog-index' %}">Home</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'blog:post-blog' %}">Post</a></li>
                {% endif %}
                <li><a class="dropdown-trigger" href="#" data-target="catagory-drop">Catagories<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger" data-target="about-drop">About<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger" data-target="account-drop">Account<i class="material-icons right">arrow_drop_down</i></a></li> 
                <li>    
                    <div class="center row">
                       <div class="col s12 " >
                            <div class="row" id="topbarsearch">
                                <div class="input-field col s6 s12">
                                    <i class=" material-icons prefix">search</i>
                                    <input type="text" placeholder="search" id="autocomplete-input" class="autocomplete" >
                                </div>
                            </div>
                        </div>
                    </div>          
                </li>
            </ul>
        </div>
    </nav>
    <!-- Mobile Nav -->
    <ul class="sidenav" id="mobile-demo">
        <li>    
            <div class="center row">
               <div class="col s12 " >
                    <div class="row" id="topbarsearch">
                        <div class="input-field col s6 s12">
                            <i class=" material-icons prefix">search</i>
                            <input type="text" placeholder="search" id="autocomplete-input" class="autocomplete" >
                        </div>
                    </div>
                </div>
            </div>          
        </li>   
        <li><a href="{% url 'blog:blog-index' %}">Home</a></li>
        <li><a href="#">Trending</a></li>
        <li><a href="#">Catagories</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'blog:post-blog' %}">Create Post</a></li>
        {% endif %}
        <li class="divider"></li>
        {% if request.user.is_authenticated %}
        <li><a href="">Profile</a></li>
        <li><a href="{% url 'accounts:account-profile' %}">Profile Settings</a></li>
        <li><a href="{% url 'accounts:account-logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'accounts:account-login' %}">Login</a></li>
        <li><a href="{% url 'accounts:account-register' %}">SignUp</a></li>
        {% endif %}

    </ul>
    <!-- Page Layout here -->
    <div class="row container">
        <div class="col s12 m8 l9">
            {% block body %}
            {% endblock body %}
        </div>
        <div class="col s12 m8 l3">
            <ul>
                {% block sidenav %}
                {% endblock sidenav %}
            </ul>
        </div>
    </div>
    <!--Footer-->
    <footer class="page-footer font-small">
        <div class='row foot-row text-center'>
          <ul class="linear-list right">
            <li>
              <a href="https://www.linkedin.com/in/pratik-c/"><i class="fab fa-2x fa-linkedin-in color"></i></a>
            </li>
            <li>
              <a href="https://twitter.com/PratikC85519965"><i class="fab fa-2x fa-twitter"></i></a>
            </li>
            <li>
              <a href="https://github.com/CodeBunny09"><i class="fab fa-2x fa-github"></i></a>
            </li>
            <li>
              <a href="https://discord.gg/Pbw95M2d7S"><i class="fab fa-2x fa-discord"></i></a>
            </li>
          </ul>
        </div>
        <div class="row foot-row text-center copyright">
          <span>© {% now "Y" %} Copyright: <a href="/about-author">Pratik</a></span>
        </div>
    </footer>
</body>
</html>