mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='blog-index'),
    path('post/<slug>', views.post, name='blog-post'),
    path('create/', views.make_post, name='post-blog'),
    path('query/', views.query, name='blog-query'),
    path('upvote/<slug>', views.upvote, name='blog-upvote'),
    path('downvote/<slug>', views.downvote, name='blog-downvote'),
    path('haha-comment/<slug>', views.haha_comment, name='comment-haha'),
    path('haha-reply/<slug>', views.haha_reply, name='reply-haha'),
    path('delete-post/<slug>', views.del_post, name='delete-post'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about-author/', include(('portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('account/', include(('accounts.urls', 'account'), namespace='accounts')),
    path('tinymce/', include('tinymce.urls')),
    path(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
import django
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericRelation
from django_resized import ResizedImageField
from tinymce.models import HTMLField
from hitcount.models import HitCountMixin, HitCount
from taggit.managers import TaggableManager
from django.shortcuts import reverse
import datetime
from django.utils import timezone


# Create your models here.
User = get_user_model()

class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=50, blank=True)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    bio = HTMLField()
    points = models.IntegerField(default=0)
    profile_pic = ResizedImageField(size=[160, 90], quality=100, upload_to="author-pfp", default=None, blank=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.user.username}{timezone.now()}')
        super(Author, self).save(*args, **kwargs)

    def __str__(self):
        return self.fullname
    
    @property
    def num_posts(self):
        return Post.objects.filter(user=self).count()

    def get_url(self):
        return reverse("accounts:profile", kwargs={
            "author_slug": self.slug
        })

class AuthorMeta(models.Model):
    user = models.OneToOneField(Author, on_delete=models.CASCADE)
    followers = models.ManyToManyField(Author, related_name='followers', blank=True)
    following = models.ManyToManyField(Author, related_name='following', blank=True)

    @property
    def get_followers(self):
        return self.followers.all().count()

    @property
    def get_following(self):
        return self.following.all().count()

    def __str__(self):
        return self.user.fullname

class Catagory(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=400, unique=True, blank=True)

    class Meta:
        verbose_name_plural = "Catagories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Catagory, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    @property
    def num_posts(self):
        return Post.objects.filter(catagory=self).count()

    @property
    def last_post(self):
        return Post.objects.filter(catagory=self).latest("date")

class Reply(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    haha = models.ManyToManyField(User)

    def __str__(self):
        return self.content[:50]

    class Meta:
        verbose_name_plural = 'Replies'
    
    @property
    def get_hahas(self):
        num_hahas = self.haha.all().count()
        return num_hahas


class Comment(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    replies = models.ManyToManyField(Reply, blank=True)
    haha = models.ManyToManyField(User)

    def __str__(self):
        return self.content[:50]

    @property
    def get_hahas(self):
        num_hahas = self.haha.all().count()
        return num_hahas


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = HTMLField(max_length=500)
    catagory = models.ManyToManyField(Catagory)
    date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    upvotes = models.ManyToManyField(User, related_name='post_upvotes')
    downvotes = models.ManyToManyField(User, related_name='post_downvotes')
    tags = TaggableManager()
    comments = models.ManyToManyField(Comment, blank=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.title}{datetime.date.today()}{self.user.user.username}{timezone.now()}')
            print(self.slug)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("blog:blog-post", kwargs={
            "slug": self.slug
        })
    
    @property
    def get_score(self):
        upvotes = self.upvotes.all().count()
        downvotes = self.downvotes.all().count()
        return upvotes - downvotes

mysite/blog/forms.py
from django import forms
from .models import Catagory, Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'catagory', 'tags']

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Author, Catagory, Post, Comment, Reply
from .utils import update_views
from django.contrib.auth.decorators import login_required
from .forms import PostForm
# Create your views here.

def index(req):
    posts = Post.objects.all()[::-1]
    num_posts = Post.objects.all().count()
    num_users = Author.objects.all().count()
    
    context = {
        'posts': posts,
        'num_posts' : num_posts,
        'num_users' : num_users,
    }

    return render(req, 'home.html', context=context)

def post(req, slug):
    post = get_object_or_404(Post, slug=slug)

    if "comment-form" in req.POST:
        author = Author.objects.get(user=req.user)
        comment = req.POST.get("comment")
        new_comment, created = Comment.objects.get_or_create(user = author, content=comment)
        post.comments.add(new_comment.id)

    if "reply-form" in req.POST:
        author = Author.objects.get(user=req.user)
        reply = req.POST.get("reply")
        comment_id = req.POST.get("comment-id")
        comment_obj = Comment.objects.get(id=comment_id)
        new_reply, created = Reply.objects.get_or_create(user = author, content=reply)
        comment_obj.replies.add(new_reply)
    
    context = {
        'post': post
    }
    update_views(req, post)
    return render(req, 'post.html', context)

def query(req):
    return render(req, 'post-query.html')

@login_required
def make_post(req):
    context = {}
    form = PostForm(req.POST or None)
    if req.method == "POST":
        if form.is_valid():
            author = Author.objects.get(user=req.user)
            new_post = form.save(commit=False)
            new_post.user = author
            new_post.save()
            form.save_m2m()
            return redirect('blog:blog-index')
    context.update({
        'form': form,
        'title': 'Create A Post'
    })

    return render(req, 'create.html', context)


@login_required
def network_stats(req):
    return render(req, 'network-stats.html')


@login_required
def upvote(req, slug):
    post = get_object_or_404(Post, slug=slug)
    post.upvotes.add(req.user)
    return redirect("blog:blog-post", slug)

@login_required
def downvote(req, slug):
    post = get_object_or_404(Post, slug=slug)
    post.downvotes.add(req.user)
    return redirect("blog:blog-post", slug)

@login_required
def haha_comment(req, slug):
    if req.method == 'POST':
        id = req.POST.get("comment_id")
        comment = get_object_or_404(Comment, id = id)
        comment.haha.add(req.user)
        return redirect("blog:blog-post", slug)
    return redirect("blog:blog-post", slug)

@login_required
def haha_reply(req, slug):
    if req.method == 'POST':
        id = req.POST.get("reply_id")
        reply = get_object_or_404(Reply, id = id)
        reply.haha.add(req.user)
        return redirect("blog:blog-post", slug)
    return redirect("blog:blog-post", slug)

@login_required
def del_post(req, slug):
    if req.method == 'POST':
        id = req.POST.get("post_id")
        post = Post.objects.get(id = id)
        post.delete()
        return redirect("accounts:profile", slug)

mysite/blog/templates/create.html
{% extends 'partials/partials.html' %}
{% load static %}
{% load hitcount_tags %}
{% block title %}
Silly | Post
{% endblock title %}
{% block body %}
<h1>Create a post</h1>
<form action="." method="POST">
    {% csrf_token %}
    <div>
        {{form}}
    </div>
    <!-- <div class="row"> Title
        <div class="input-field col s6">
            <input id="title" type="text" data-length="100">
            <label for="title"><b>Title</b></label>
        </div>
    </div>
    <div class="row"> Content -->
        <!-- <div class="input-field col s12">
            <textarea id="content" class="materialize-textarea" data-length="500"></textarea>
            <label for="content">Content</label>
        </div>
    </div>
    <div class="row"> Catagories -->
        <!-- <div class="col s3">
            <a class='dropdown-trigger btn' href='#' data-target='dropdown1'>Catagories</a>
        
            <ul id='dropdown1' class='dropdown-content'>
              <li><a href="#!">Cat 1</a></li>
              <li><a href="#!">Cat 2</a></li>
              <li><a href="#!">Cat 3</a></li>
            </ul>
        </div>
        <div class="col s9">
            <p>
                <ul class="linear-list">
                    <li>
                        <div class="chip">
                            <a href="#">Cat 1</a>
                        </div>
                    </li>
                    <li>
                        <div class="chip">
                            <a href="#">Cat 2</a>
                        </div>
                    </li>
                    <li>
                        <div class="chip">
                            <a href="#">Cat 3</a>
                        </div>
                    </li>
                </ul>
            </p>
        </div>
    </div> -->
    <button class="btn waves-effect waves-light red" type="submit" name="action">Post
        <i class="material-icons right">send</i>
    </button>
</form>
{% endblock body %}
{% block sidenav %}
<!-- Sidenav -->
<li href="#" class="waves-effect collection-item"><h5>Trending</h5></li>
<ul class="collection">
    <li href="#" class="collection-item">Post Title 1</li>
    <li href="#" class="collection-item">Post Title 2</li>
    <li href="#" class="collection-item">Post Title 3</li>
    <li href="#" class="collection-item">Post Title 4</li>
    <li href="#" class="collection-item">Post Title 5</li>
</ul>
<li href="#" class="waves-effect collection-item"><h5>Recents</h5></li>
<ul class="collection">
    <li href="#" class="collection-item">Post Title 1</li>
    <li href="#" class="collection-item">Post Title 2</li>
    <li href="#" class="collection-item">Post Title 3</li>
    <li href="#" class="collection-item">Post Title 4</li>
    <li href="#" class="collection-item">Post Title 5</li>
</ul>
<li href="#" class="waves-effect collection-item"><h5>Catagories</h5></li>
<ul class="collection">
    <li href="#" class="waves-effect collection-item">Cat 1</li>
    <li href="#" class="waves-effect collection-item">Cat 2</li>
    <li href="#" class="waves-effect collection-item">Cat 3</li>
    <li href="#" class="waves-effect collection-item">Cat 4</li>
</ul>
{% endblock sidenav %}

mysite/blog/templates/home.html
{% extends 'partials/partials.html' %}
{% load hitcount_tags %}
{% block title %}
Silly | Home
{% endblock title %}
{% block body %}
<div class="container">
    <h2 class="header">Posts by all users</h2>
    <!--Card Start-->
    {% for post in posts %}
    <div class="card horizontal">
        <div class="card-stacked">
            <div class="card-content">
                <h3>{{post.title}}</h3>
                <ul class="linear-list">
                    {% for cat in post.catagory.all %}
                    <li>
                        <div class="chip">
                            <a href="#">{{cat}}</a>
                          </div>
                    </li>
                    {% endfor %}
                </ul>
                <p>{{post.content | safe}}</p>
                <ul class="linear-list">
                    {% for tag in post.tags.all %}
                    <li>
                        <a href="#">#{{tag}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card-action">
                <a class="waves-effect waves-light btn btn-small" href="{{post.get_url}}">View Post</a>
                <span class="right"> {% get_hit_count for post %} Views</span><br>
                <span class="right">{{post.points}} Points</span>
            </div>
            <div class="card-content card-footer">
                Post By <a href="{{post.user.get_url}}">{{post.user.fullname | title}}</a> on <a>{{post.date | date}}</a>
            </div>
        </div>
    </div>
    {% endfor %}
    <!--Card End-->
</div>
{% endblock body %}
<!-- Sidenav -->
{% block sidenav %}
<li href="#" class="waves-effect collection-item"><h5>Trending Catagories</h5></li>
<ul class="collection">
    <li href="#" class="waves-effect collection-item">Cat 1</li>
    <li href="#" class="waves-effect collection-item">Cat 2</li>
    <li href="#" class="waves-effect collection-item">Cat 3</li>
    <li href="#" class="waves-effect collection-item">Cat 4</li>
    <li href="#" class="waves-effect collection-item">Cat 5</li>
</ul>
<li href="#" class="waves-effect collection-item"><h5>Trending Authors</h5></li>
<ul class="collection">
    <li href="#" class="waves-effect collection-item">Author A</li>
    <li href="#" class="waves-effect collection-item">Author B</li>
    <li href="#" class="waves-effect collection-item">Author C</li>
    <li href="#" class="waves-effect collection-item">Author D</li>
    <li href="#" class="waves-effect collection-item">Author E</li>
</ul>
<ul>
    <table>
        <tr>
            <th>Users</td>
            <td>{{num_users}}</td>
        </tr>
        <tr>
            <th>Posts</td>
            <td>{{num_posts}}</td>
        </tr>
    </table>
</ul>
{% endblock sidenav %}

mysite/blog/templates/network-stats.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
    <!--Material CSS CDNs-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!--Custom JS-->
    <script type="text/javascript" src="{% static 'js/blog/index.js' %}"></script>

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/blogs/style.css' %}">
    
    <title>{% block title %}Network Stats{% endblock title %}</title>
</head>
<body>
    <div class="container">
        <ul class="tabs row">
            <li class="tab col s6"><a href="#followers">Followers</a></li>
            <li class="tab col s6"><a href="#followings">Following</a></li>
        </ul>
        <div class="row">
        <div id="followers" class="container col s12">
            <ul class="collection">
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Darlene</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Follow Back</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Elliot</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Follow Back</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Sheyla</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Follow Back</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Whiterose</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Follow Back</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Dom</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Follow Back</a>
                </li>
            </ul>
        </div>
        <div id="followings" class="container col s12">
            <ul class="collection">
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Phillip</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Unfollow</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Tyrell</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Unfollow</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Sheyla</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Unfollow</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Elliot</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Unfollow</a>
                </li>
                <li class="collection-item avatar">
                    <img src="" alt="" class="circle">
                    <span class="title">Rohit</span>
                    <a href="#" class="secondary-content waves-effect waves-light btn">Unfollow</a>
                </li>
            </ul>
        </div>
        </div>
    </div>
</body>
</html>

mysite/blog/templates/post.html
{% extends 'partials/partials.html' %}
{% load static %}
{% load hitcount_tags %}
{% block title %}
Silly | {{post.title}}
{% endblock title %}
{% block body %}
<div class="container post-container">
    <!-- User data -->
    <div class="row">
        <ul class="collection">
            <a href="{{post.user.get_url}}" class="brand-logo black-text">
                <li class="collection-item avatar">
                    <img src="{{post.user.profile_pic.url}}" alt="{{post.user.fullname}}" class="circle">
                    <span class="username-header title"><h5>{{post.user.fullname | title}}</h5></span>
                    <a href="#" class="secondary-content">{{post.date | date}}</a>
                </li>
            </a>
        </ul>
    </div>
    <!-- Post heading and score actions -->
    <div class="row">
        <div class="col s2 center-align">
            <form method="POST" action="{% url 'blog:blog-upvote' post.slug%}">
                {% csrf_token %}
                <button type="submit" class="btn-floating waves-effect waves-light white" name='post_id' value="{{ post.id }}">
                    <i class="material-icons red-text medium">
                        expand_less
                    </i>
                </button><br>
            </form>
            <form method="POST" action="{% url 'blog:blog-downvote' post.slug%}">
                {% csrf_token %}
                <span>{{post.get_score}}</span><br>
                <button type="submit" class="btn-floating waves-effect waves-light white" name='post_id' value="{{ post.id }}">
                    <i class="material-icons red-text medium">
                        expand_more
                    </i>
                </button><br>
            </form>
            <span>Views: {% get_hit_count for post %}</span><br>
            <a class="btn-floating white waves-effect waves-light"><i id="share" class="material-icons small red-text tooltipped" data-position="right" data-tooltip="Share">share</i></a>
        </div>
        <div class="col s10">
            <a id="bookmark" onclick="M.toast({html: 'Bookmark Added!', classes: 'rounded'})" class="secondary-content tooltipped" data-position="left" data-tooltip="Bookmark This Post!"><i id="bookmark-icon" class="material-icons medium red-text">bookmark_border</i></a>
            <h3>{{post.title}}</h3>
            <p>
                <ul class="linear-list">
                    {% for cat in post.catagory.all %}
                    <li>
                        <div class="chip">
                            <a href="#">{{cat}}</a>
                          </div>
                    </li>
                    {% endfor %}
                </ul>
                <!-- Tags -->
                <ul class="linear-list">
                    {% for tag in post.tags.all %}
                    <li>
                        <a href="#">#{{tag}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </p>
        </div>
    </div>
    <!-- Descriptions -->
    <div class="row">
        <p>{{post.content | safe}}</p>
    </div>
    <!-- Comment Post -->
    <div class="row">
        <form action="{{post.geturl}}" class="col s12" name="comment-form" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    <textarea name="comment" id="textarea1" class="materialize-textarea"></textarea>
                    <label for="textarea1">Comment...</label>
                    <button class="btn waves-effect waves-light red" name="comment-form" type="submit">Post
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    {% for comment in post.comments.all %}
    <!-- Comments -->
    <ul class="collection">
        <li class="collection-item avatar">
            <a href="{{comment.user.get_url}}" class="brand-logo black-text">
                <img src="{{comment.user.profile_pic.url}}" alt="{{comment.user.fullname | title}}" class="circle">
                <span href="{{post.user.get_url}}" class="title">{{comment.user.fullname | title}}</span>
            </a>
            <p>{{comment.date | date}} <br>
               {{comment.content}}
            </p>
            <div class="row comment-controls">
                <ul class="collection no-border">
                    <li  class="collection-item">
                        <form method="POST" action="{% url 'blog:comment-haha' post.slug%}">
                            {% csrf_token %}
                            <button type="submit" class="waves-effect waves-light btn-small red" name="comment_id" value="{{comment.id}}">
                                <i class="material-icons small white-text">sentiment_very_satisfied</i>
                            </button>
                            <span class="text-center">{{comment.get_hahas}}</span>
                        </form>
                    </li>
                    <li  class="waves-effect collection-item">
                        <form action="{{post.get_url}}" method="POST">
                            {% csrf_token %}
                            <div class="input-field no-border">
                                <textarea name="reply" id="comment{{ comment.id }}" class="materialize-textarea"></textarea>
                                <label for="comment{{ comment.id }}">Reply...</label>
                                <button class="btn waves-effect waves-light red" type="submit" name="reply-form">Send
                                    <i class="material-icons right">send</i>
                                </button>
                                <input name="comment-id" value={{ comment.id }} type="hidden" >
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </li>
        <!-- Reply -->
        {% for reply in comment.replies.all %}
        <li class="collection-item avatar reply">
            <a href="{{reply.user.get_url}}" class="brand-logo black-text">
                <img src="{{reply.user.profile_pic.url}}" alt="{{reply.user.fullname | title}}" class="circle">
                <span  href="{{post.user.get_url}}" class="title">{{ reply.user.fullname | title }}</span>
            </a>
            <p>{{ reply.date | date }}<br>
               {{ reply.content }}
            </p>
            <div class="col s2 right" style="position: absolute; top:10%; right:6%;">
                <form method="POST" action="{% url 'blog:reply-haha' post.slug%}">
                    {% csrf_token %}
                    <button type="submit" class="waves-effect waves-light btn-small red" name="reply_id" value="{{reply.id}}">
                        <i class="material-icons small white-text">sentiment_very_satisfied</i>
                    </button>
                    <span class="text-center">{{reply.get_hahas}}</span>
                </form>
            </div>
        </li>
        {% endfor %}
        <!-- Reply End -->
    </ul>
    <!-- Comment End -->
    <!-- Comments -->
    {% endfor %}
</div>
{% endblock body %}
{% block sidenav %}
<!-- Sidenav -->
<li href="#" class="waves-effect collection-item"><h5>Trending</h5></li>
<ul class="collection">
    <li href="#" class="collection-item">Post Title 1</li>
    <li href="#" class="collection-item">Post Title 2</li>
    <li href="#" class="collection-item">Post Title 3</li>
    <li href="#" class="collection-item">Post Title 4</li>
    <li href="#" class="collection-item">Post Title 5</li>
</ul>
<li href="#" class="waves-effect collection-item"><h5>Recents</h5></li>
<ul class="collection">
    <li href="#" class="collection-item">Post Title 1</li>
    <li href="#" class="collection-item">Post Title 2</li>
    <li href="#" class="collection-item">Post Title 3</li>
    <li href="#" class="collection-item">Post Title 4</li>
    <li href="#" class="collection-item">Post Title 5</li>
</ul>
<li href="#" class="waves-effect collection-item"><h5>Catagories</h5></li>
<ul class="collection">
    <li href="#" class="waves-effect collection-item">Cat 1</li>
    <li href="#" class="waves-effect collection-item">Cat 2</li>
    <li href="#" class="waves-effect collection-item">Cat 3</li>
    <li href="#" class="waves-effect collection-item">Cat 4</li>
</ul>
{% endblock sidenav %}